# Generated by Django 5.2.6 on 2025-10-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0003_etudiant_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='imageProfil',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
