# Generated by Django 5.2.6 on 2025-10-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0004_etudiant_imageprofil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='imageProfil',
            field=models.ImageField(blank=True, default='fatou.jpg', null=True, upload_to=''),
        ),
    ]
