# Generated by Django 5.2.6 on 2025-10-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0006_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='pdf_file',
            field=models.FileField(null=True, upload_to='documents/pdfs/'),
        ),
    ]
