# Generated by Django 5.2.6 on 2025-10-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0007_etudiant_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='pdf_file',
            field=models.FileField(null=True, upload_to='documents/pdf'),
        ),
    ]
