# Generated by Django 5.2.6 on 2025-11-01 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0010_filiere_alter_etudiant_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='filiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='myFirstApp.filiere'),
        ),
    ]
